### ISSUE TITLE
Error at buid

### ISSUE THREAD

**Issue by sniicker** [okhiroyuki/redmobile-modules-generator#4]
Hi, at first thank you very much for your realy nice RedMobile feature. I love it.

Im running on a Win10 Machine and i what to set up a custom modul for my phone.
Im not a programmer so the Github world is sometimes realy hard for me, but most oft the time i can handle it after some time, but here i think i need your help..!

Can you please helpt me how to get it work.

things i have done:

- Created a new folder in windows
- cd into that folder
- git clone https://github.com/okhiroyuki/redmobile-modules-generator.git
- cd into that gernerated folder
- npm i
- npm i node-red-contrib-telegrambot
- npm run build

now i get a error msg.
![grafik](https://user-images.githubusercontent.com/67097444/141119885-14c50464-f7d2-4206-88da-f6dcc39091f0.png)

In the package.json file the telegrambot is listed.
Before i start the build the noe_modules folder is there, but at that time the error comes, the folder is also gone??

I dont know what do do now...

**Comment by sniicker** [comment]
No sry

**Comment by Asadsaeed003091** [comment]
I am having the same issue, this is a paid app and paid feature but still it doesn't works.

**Comment by sniicker** [comment]
yes it's annoying - @okhiroyuki why won't you help?

**Comment by Marlark** [comment]
I have on and off come back to trying to figure this one out as you guys.. but i managed to get past the above error today because i figured out that there was a folder missing. When i created this folder "node_modules" in the generator folder and when i did the npm i. it populates that folder with all the modules incl the once you install ontop. then i got past this error and the code creates the folder "dist" itself when running.. however it can not exist that folder when you run because it will spit out a error if the folder is there that it cant create it.

It looks like he is just compressing what is in that folder with Gzip format  level 9 ... wish means you should be able to dump what is in the node_modules folder in with 7zip with zip archive format and complevel 9  should be deflate method. Am going to test if that works.

But i am getting the cmd window upp but it spit out some new errors when trying to do stuff in it that i cant catch... but it looks like it is failing on the compression file creation i have noticed when i saw how he compresses the file together and wondering if that the above is a semi workaround to get it working ... but going to test if that works.

**Comment by bikeortrike** [comment]
I appreciate the work you're doing on this. Did you have any luck moving
this forward beyond what you wrote here?

Thanks

**Comment by okhiroyuki** [comment]
@sniicker 
Have you tried the latest code and cannot create it successfully?

**Comment by okhiroyuki** [comment]
I have confirmed that the latest code builds fine on Windows 10.
a122835cf2e28117044d0ef74be4763faf53c6f9

Note that there was a case where the build failed if the dist folder was present, so a response has been put in place.
